version: '3.6'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    user: "0:0"
    environment:
      - DEBUG=1
      - LOCALSTACK_HOSTNAME=localhost
      - TEST_AWS_ACCOUNT_ID=000000000000
      - AWS_DEFAULT_REGION=us-west-2
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
      - KINESIS_STREAM_SHARDS=1
      - KINESIS_ERROR_PROBABILITY=0.0
      - KINESIS_STREAM_NAME=kinesis-stream
      - KINESIS_PROVIDER=kinesalite
      - SERVICES=apigateway,lambda,s3,dynamodb
      - USE_SSL=false
    ports:
      - "4566:4566" 
      - "4510-4559:4510-4559" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/data:/.tmp/localstack/data 
      - ./certs:/etc/localstack/certs 

